name: Deploy to DigitalOcean
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build and push client
        env:
          REGISTRY: registry.digitalocean.com/${{ secrets.DO_REGISTRY }}
        run: |
          docker build -t ${REGISTRY}/librechat-client:${GITHUB_SHA::7} -t ${REGISTRY}/librechat-client:latest -f client/Dockerfile client/
          docker push ${REGISTRY}/librechat-client:${GITHUB_SHA::7}
          docker push ${REGISTRY}/librechat-client:latest

      - name: Update deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/LibreChat
            echo "REGISTRY=registry.digitalocean.com/${{ secrets.DO_REGISTRY }}" > .env.registry
            docker compose -f deploy-compose.yml --env-file .env --env-file .env.registry up -d
