name: Deploy to DigitalOcean
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          known_hosts: unnecessary
          name: librechat_deploy
          if_key_exists: replace

      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Start build
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/librechat_deploy ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} '
            cd ~/LibreChat &&
            git fetch origin production &&
            git checkout production &&
            git pull origin production &&
            chmod +x build-client.sh &&
            nohup ./build-client.sh > /dev/null 2>&1 &
          '
      
      - name: Wait and check build
        run: |
          echo "Waiting for build to complete..."
          sleep 30
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/librechat_deploy ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} '
            cd ~/LibreChat &&
            if [ -f build-client.log ]; then
              cat build-client.log
              if tail -n1 build-client.log | grep -q "status 0"; then
                echo "Build succeeded, deploying..."
                docker compose -f deploy-compose.yml up -d
              else
                echo "Build failed!"
                exit 1
              fi
            else
              echo "No build log found!"
              exit 1
            fi
          '
