name: Deploy to DigitalOcean
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          known_hosts: unnecessary
          name: librechat_deploy
          if_key_exists: replace

      - name: Deploy to DigitalOcean
        run: |
          ssh -i ~/.ssh/librechat_deploy ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} '
            cd ~/LibreChat &&
            git fetch origin production &&
            git checkout production &&
            git pull origin production &&
            docker compose -f deploy-compose.yml down &&
            docker compose -f deploy-compose.yml up -d
          '