name: Deploy to DigitalOcean
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          known_hosts: unnecessary
          name: librechat_deploy
          if_key_exists: replace

      - name: Copy and run deploy script
        run: |
          scp -i ~/.ssh/librechat_deploy -o StrictHostKeyChecking=no deploy.sh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/home/ember/LibreChat/
          ssh -i ~/.ssh/librechat_deploy -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} 'cd /home/ember/LibreChat && chmod +x deploy.sh && nohup ./deploy.sh > deploy.log 2>&1 &'
